### ISSUE TITLE
Is the backend in Firebase Realtime DB or Cloud FireStore?

### ISSUE THREAD

**Issue by aravindemis** [ruppysuppy/Pizza-Man#2]
Thanks for this demo project, trying to bring it up and running and I could.

But while updating the address, I see the below error in console.

```

> [2021-06-10T11:32:01.023Z]  @firebase/firestore: Firestore (7.17.2): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=failed-precondition]: The Cloud Firestore API is not available for Datastore Mode projects.
> This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

```

Do I need to configure Firestore to run it or Firebase Realtime DB is enough?

Any help to resolve this will be much appreciated!

**Comment by ruppysuppy** [comment]
The example data (`/src/firebase/exampleData.json`) needs to be imported in the **Firebase Realtime Database**, **Firestore** is required for storing the dynamic data like the user address and previous orders. You will be required to configure **Firestore** and add an index as well:

```js
{
    collection: "orders",
    fields: {
        uid: Ascending,
        ts: Descending,
    },
    queryScope: Collection
}
```

**Comment by rkscodes** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30290728/143621734-23047e72-a4c0-4898-ba36-35ab0c8471ba.png">
I am getting this error, I am not sure how to configure Firestore, I have added index which you suggested above. 

<img width="951" alt="image" src="https://user-images.githubusercontent.com/30290728/143621833-562cf7f2-3d9e-47ef-ba54-6da0a6499fa0.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/30290728/143621850-2bd5522f-bee2-4b97-8e65-7af55af3b8ee.png">

**Comment by ruppysuppy** [comment]
@rkscodes you have the wrong rules, your rules will restrict anyone from reading/writing the data, use:

```cpp
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

**Comment by rkscodes** [comment]
Yes you are right, it resolved the issue, thanks.
